gText_Item_IronSickle_Name:
    .string "鉄のカマ"
    .align 2, 0

gText_Item_IronSickle_Description:
    .string "カマ\r\n牧草、雑草を刈り取れる。\r\n作物も刈ってしまうので注意！"
    .align 2, 0

gText_Item_CopperSickle_Name:
    .string "銅のカマ"
    .align 2, 0

gText_Item_CopperSickle_Description:
    .string "銅のカマ\r\n牧草、雑草を刈り取れる。\r\n作物も刈ってしまうので注意！"
    .align 2, 0

gText_Item_SilverSickle_Name:
    .string "銀のカマ"
    .align 2, 0

gText_Item_SilverSickle_Description:
    .string "銀のカマ\r\n牧草、雑草を刈り取れる。\r\n作物も刈ってしまうので注意！"
    .align 2, 0

gText_Item_GoldSickle_Name:
    .string "金のカマ"
    .align 2, 0

gText_Item_GoldSickle_Description:
    .string "金のカマ\r\n牧草、雑草を刈り取れる。\r\n作物も刈ってしまうので注意！"
    .align 2, 0

gText_Item_MystrileSickle_Name:
    .string "ミスリルのカマ"
    .align 2, 0

gText_Item_MystrileSickle_Description:
    .string "ミスリルのカマ\r\n牧草、雑草を刈り取れる。\r\n作物も刈ってしまうので注意！"
    .align 2, 0

gText_Item_CursedSickle_Name:
    .string "呪われたカマ"
    .align 2, 0

gText_Item_CursedSickle_Description:
    .string "呪われたカマ\r\n装備すると外せなくなる！\r\n教会に行けば外してもらえる。"
    .align 2, 0

gText_Item_BlessedSickle_Name:
    .string "祝福のカマ"
    .align 2, 0

gText_Item_BlessedSickle_Description:
    .string "祝福のカマ\r\n呪いがとけたカマ！\r\n"
    .align 2, 0

gText_Item_MythicSickle_Name:
    .string "賢者のカマ"
    .align 2, 0

gText_Item_MythicSickle_Description:
    .string "賢者のカマ\r\n牧草、雑草を刈り取れる。\r\n作物も刈ってしまうので注意！"
    .align 2, 0