#include "supermarket_text.hh"

#include "item.hh"

SupermarketCatalogEntry const gSupermarketCropSeedCatalog[] = {
    { ITEM_TOOL_SEEDS_TURNIP, 120 },
    { ITEM_TOOL_SEEDS_POTATO, 150 },
    { ITEM_TOOL_SEEDS_CUCUMBER, 200 },
    { ITEM_TOOL_SEEDS_STRAWBERRY, 150 },
    { ITEM_TOOL_SEEDS_TOMATO, 200 },
    { ITEM_TOOL_SEEDS_CORN, 300 },
    { ITEM_TOOL_SEEDS_ONION, 150 },
    { ITEM_TOOL_SEEDS_PUMPKIN, 500 },
    { ITEM_TOOL_SEEDS_EGGPLANT, 120 },
    { ITEM_TOOL_SEEDS_CARROT, 300 },
    { ITEM_TOOL_SEEDS_SWEET_POTATO, 300 },
    { ITEM_TOOL_SEEDS_SPINACH, 200 },
    { ITEM_TOOL_SEEDS_GRASS, 500 },
};

#if defined(REGION_JP)
#define FOMT_TEXT_SUPERMARKET_PRIMARY
#include FOMT_TEXT_INCLUDE(supermarket.cc)
#undef FOMT_TEXT_SUPERMARKET_PRIMARY
#else
#define FOMT_TEXT_SUPERMARKET_PRIMARY
#include FOMT_TEXT_INCLUDE(supermarket.cc)
#undef FOMT_TEXT_SUPERMARKET_PRIMARY
#endif

SupermarketCatalogEntry const gSupermarketAdditionalSeedCatalog[] = {
    { ITEM_TOOL_SEEDS_SPINACH, 100 },
    { ITEM_TOOL_SEEDS_GREEN_PEPPER, 100 },
    { ITEM_TOOL_SEEDS_GRASS, 50 },
    { ITEM_TOOL_SEEDS_MOON_DROP, 50 },
    { ITEM_TOOL_SEEDS_PINK_CAT, 50 },
    { ITEM_TOOL_SEEDS_MAGIC, 100 },
    { ITEM_TOOL_SEEDS_TOY_FLOWER, 100 },
    { 0, 0 },
};

#if defined(REGION_JP)
#define FOMT_TEXT_SUPERMARKET_SECONDARY
#include FOMT_TEXT_INCLUDE(supermarket.cc)
#undef FOMT_TEXT_SUPERMARKET_SECONDARY
#else
#define FOMT_TEXT_SUPERMARKET_SECONDARY
#include FOMT_TEXT_INCLUDE(supermarket.cc)
#undef FOMT_TEXT_SUPERMARKET_SECONDARY
#endif
